# render.yaml — BackTradz (Blueprint)

envVarGroups:
  - name: backtradz-prod   # EXACTEMENT le nom du Environment Group

services:
  # ---------- BACKEND (FastAPI) ----------
  - type: web
    name: backtradz-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    # change "main:app" si ton fichier s'appelle autrement (ex: app.py -> "app:app")
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - fromGroup: backtradz-prod

  # ---------- FRONTEND (Vite) ----------
  - type: static
    name: backtradz-frontend
    plan: free
    rootDir: frontend-react       # adapte si ton dossier est "frontend" ou "frontend-react"
    buildCommand: "npm ci && npm run build"
    staticPublishPath: dist
    envVars:
      - fromGroup: backtradz-prod
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
