# render.yaml — backend only (start at repo root)
envVarGroups:
  - name: backtradz-prod

services:
  - type: web
    name: backtradz-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      - fromGroup: backtradz-prod
