# render.yaml — BackTradz (Blueprint)

envVarGroups:
  - name: backtradz-prod     # <- ce nom doit être EXACTEMENT celui créé dans Render

services:
  # ---------- BACKEND (FastAPI) ----------
  - type: web
    name: backtradz-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - fromGroup: backtradz-prod
    healthCheckPath: /health   # adapte si tu n’as pas /health

  # ---------- FRONTEND (Vite) ----------
  - type: static
    name: backtradz-frontend
    rootDir: frontend-react
    buildCommand: "npm ci && npm run build"
    staticPublishPath: dist
    envVars:
      - fromGroup: backtradz-prod
    # (optionnel) pour éviter le cache agressif pendant la V1
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
